#!/bin/bash
echo Testing...
go test ./...

echo Benchmarking...
go test -bench . -count 5

echo Checking coverage...
echo You might need to run go get golang.org/x/tools/cmd/cover
go test -coverprofile enaml